export default {
  POSTGRESQL_TYPE: '',
  POSTGRESQL_HOST: '',
  POSTGRESQL_PORT: 5432,
  POSTGRESQL_DATABASE_NAME: '',
  POSTGRESQL_USERNAME: '',
  POSTGRESQL_PASSWORD: '',

  LOGGING: ['query', 'error', 'info', 'warn'],
  LOGGER: 'file',

  ACCESS_SECRET_KEY: '',
  REFRESH_SECRET_KEY: '',
  ACCESS_TOKEN_EXPIRESIN: '',
  REFRESH_TOKEN_EXPIRESIN: '',
  VERIFY_TOKEN_EXPIRESIN: '',

  SALT: '',

  EMAIL_PASSWORD: '',
  EMAIL_USERNAME: '',
};
